import { useEffect, useState } from 'react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import RiskBadge from '../components/RiskBadge.jsx'
import Section from '../components/Section.jsx'
import Loader from '../components/Loader.jsx'
import Stepper from '../components/Stepper.jsx'
import { api } from '../services/api.js'
import { useFlow } from '../context/FlowContext.jsx'

// Strip the [DEMO OUTPUT - ...] prefix the demo provider injects into summary text
// so we can present it cleanly. The stored value is unchanged.
function stripDemoPrefix(text) {
  return text.replace(/^\[DEMO OUTPUT[^\]]*\]\s*/i, '')
}

// Extract structured stat cards from the known demo-provider observation phrasing.
// Unrecognized observations (e.g. free-form text from a real AI provider) fall back
// to plain list rendering — nothing is ever fabricated.
function parseObservationStats(observations) {
  const stats = []
  const rest = []

  for (const obs of observations ?? []) {
    let consumed = false

    const severity = obs.match(/severity is (\d+)\/10/)
    if (severity) {
      stats.push({ label: 'Severity', value: `${severity[1]} / 10` })
      consumed = true
    }
    const onset = obs.match(/with an? (gradual|sudden) onset/)
    if (onset) {
      stats.push({ label: 'Onset', value: onset[1][0].toUpperCase() + onset[1].slice(1) })
      consumed = true
    }
    const duration = obs.match(/onset over (.+?)\.?$/)
    if (duration) {
      stats.push({ label: 'Duration', value: duration[1] })
      consumed = true
    }
    const answers = obs.match(/(\d+) follow-up answer/)
    if (answers) {
      stats.push({ label: 'Follow-up', value: `${answers[1]} answer${answers[1] !== '1' ? 's' : ''}` })
      consumed = true
    }
    const report = obs.match(/attached with (\d+) extracted value/)
    if (report) {
      stats.push({ label: 'Report', value: `${report[1]} value${report[1] !== '1' ? 's' : ''}` })
      consumed = true
    }

    if (!consumed) rest.push(obs)
  }

  return { stats, rest }
}

function DemoNotice() {
  return (
    <div className="demo-notice" role="note" aria-label="Demo mode notice">
      <span className="demo-notice-label">Demo mode</span>
      <span>
        This assessment was generated by a deterministic synthetic engine — no external AI was
        contacted and no real medical inference was performed. It is for demonstration purposes
        only.
      </span>
    </div>
  )
}

function StatCards({ stats }) {
  if (!stats.length) return null
  return (
    <div className="stat-grid">
      {stats.map((s) => (
        <div className="stat-card" key={s.label}>
          <div className="stat-label">{s.label}</div>
          <div className="stat-value">{s.value}</div>
        </div>
      ))}
    </div>
  )
}

function List({ items, marker = '•' }) {
  if (!items?.length) return <p style={{ color: 'var(--text-2)' }}>Nothing reported.</p>
  return (
    <ul className="list-check">
      {items.map((item, i) => (
        <li key={i}>
          <span className="marker" aria-hidden="true">{marker}</span>
          <span>{item}</span>
        </li>
      ))}
    </ul>
  )
}

function NumberedSteps({ steps }) {
  if (!steps?.length) return <p style={{ color: 'var(--text-2)' }}>Nothing reported.</p>
  return (
    <ol className="numbered-list">
      {steps.map((step, i) => (
        <li className="numbered-item" key={i}>
          <span className="num" aria-hidden="true">{String(i + 1).padStart(2, '0')}</span>
          <span>{step}</span>
        </li>
      ))}
    </ol>
  )
}

function QuestionCards({ questions }) {
  if (!questions?.length) return <p style={{ color: 'var(--text-2)' }}>Nothing reported.</p>
  return (
    <div className="q-card-list">
      {questions.map((q, i) => (
        <div className="q-card" key={i}>{q}</div>
      ))}
    </div>
  )
}

export default function ResultsPage() {
  const { analysisId } = useParams()
  const navigate = useNavigate()
  const { reset } = useFlow()

  const [analysis, setAnalysis] = useState(null)
  const [error, setError] = useState(null)

  useEffect(() => {
    let cancelled = false
    const id = Number(analysisId)
    if (!Number.isFinite(id)) {
      setError('Invalid analysis reference.')
      return
    }
    api
      .getAnalysis(id)
      .then((data) => {
        if (!cancelled) setAnalysis(data)
      })
      .catch((err) => {
        if (!cancelled) setError(err.message)
      })
    return () => {
      cancelled = true
    }
  }, [analysisId])

  function startNew() {
    reset()
    navigate('/profile')
  }

  if (error) {
    return (
      <div className="card">
        <h2>Could not load the assessment</h2>
        <div className="error-box" role="alert">{error}</div>
        <button className="btn btn-secondary" onClick={startNew}>Start a new assessment</button>
      </div>
    )
  }

  if (!analysis) {
    return (
      <div className="card">
        <Loader title="Loading your assessment" message="Retrieving your results…" />
      </div>
    )
  }

  const isDemo = analysis.source === 'demo'
  const displaySummary = isDemo ? stripDemoPrefix(analysis.summary) : analysis.summary
  const { stats, rest } = parseObservationStats(analysis.observations)

  return (
    <div className="fade-in">
      <Stepper current={4} />

      {/* ── Header ──────────────────────────────────────────────────── */}
      <div className="card">
        <div className="page-head">
          <h2>Preliminary Health Assessment</h2>
          <RiskBadge level={analysis.risk_level} />
          {analysis.safety_override && (
            <span
              className="demo-chip"
              title="The safety layer raised the risk level based on detected urgent warning signs."
            >
              ⚠ Safety escalation applied
            </span>
          )}
        </div>

        {isDemo && <DemoNotice />}

        {analysis.risk_level === 'HIGH' && (
          <div className="alert alert-HIGH" style={{ marginTop: 16 }} role="alert">
            <strong>Urgent care may be needed.</strong> Based on what you described, please seek
            medical attention promptly. If symptoms are severe or worsening right now, contact
            local emergency services.
          </div>
        )}

        <p style={{ marginTop: 16, marginBottom: 0, lineHeight: 1.65, fontSize: 15 }}>
          {displaySummary}
        </p>

        {analysis.symptoms.length > 0 && (
          <div style={{ marginTop: 18 }}>
            <div className="section-label">Symptoms you reported</div>
            <div className="chips">
              {analysis.symptoms.map((s, i) => (
                <span className="chip" key={i}>{s}</span>
              ))}
            </div>
          </div>
        )}
      </div>

      {/* ── Detail grid ─────────────────────────────────────────────── */}
      <div className="results-grid">
        {analysis.red_flags.length > 0 && (
          <Section title="Urgent warning signs detected" span2>
            <div className="alert alert-HIGH" style={{ marginBottom: 0 }} role="alert">
              The following urgent signals were found in what you entered. Please seek medical
              attention promptly.
              <ul style={{ marginTop: 8 }}>
                {analysis.red_flags.map((flag, i) => <li key={i}>{flag}</li>)}
              </ul>
            </div>
          </Section>
        )}

        <Section title="Observations">
          <StatCards stats={stats} />
          {rest.length > 0 && (
            <div style={stats.length ? { marginTop: 12 } : undefined}>
              <List items={rest} />
            </div>
          )}
          {stats.length === 0 && rest.length === 0 && (
            <p style={{ color: 'var(--text-2)' }}>Nothing reported.</p>
          )}
        </Section>

        <Section title="Possible concerns" subtitle="These are possibilities based on general patterns — not diagnoses.">
          <List items={analysis.possible_concerns} />
        </Section>

        <Section title="Recommended next steps" span2>
          <NumberedSteps steps={analysis.recommended_next_steps} />
        </Section>

        <Section title="Questions to ask your doctor" span2>
          <QuestionCards questions={analysis.questions_for_doctor} />
        </Section>

        <Section title="Limitations of this assessment" span2>
          <p style={{ color: 'var(--text-2)', fontSize: 14, margin: 0 }}>{analysis.limitations}</p>
        </Section>
      </div>

      {/* ── Disclaimer + actions ────────────────────────────────────── */}
      <div className="card">
        <div className="alert alert-warn" style={{ marginBottom: 16 }}>
          {analysis.disclaimer}
        </div>
        <div className="btn-row" style={{ marginTop: 0 }}>
          <Link to="/history" className="btn btn-secondary">View history</Link>
          <button className="btn btn-primary" onClick={startNew}>Start new assessment</button>
        </div>
      </div>
    </div>
  )
}
