import { useEffect, useState } from 'react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import RiskBadge from '../components/RiskBadge.jsx'
import Section from '../components/Section.jsx'
import Loader from '../components/Loader.jsx'
import Stepper from '../components/Stepper.jsx'
import { api } from '../services/api.js'
import { useFlow } from '../context/FlowContext.jsx'

// Strip the [DEMO OUTPUT - ...] prefix the demo provider injects into summary text
// so we can present it as a styled notice rather than raw developer markup.
function stripDemoPrefix(text) {
  return text.replace(/^\[DEMO OUTPUT[^\]]*\]\s*/i, '')
}

function List({ items, marker = '•' }) {
  if (!items?.length) return <p style={{ color: 'var(--muted)' }}>Nothing reported.</p>
  return (
    <ul className="list-check">
      {items.map((item, i) => (
        <li key={i}>
          <span className="marker" aria-hidden="true">{marker}</span>
          <span>{item}</span>
        </li>
      ))}
    </ul>
  )
}

function DemoNotice() {
  return (
    <div
      style={{
        display: 'flex',
        alignItems: 'flex-start',
        gap: 10,
        background: 'var(--warn-soft)',
        border: '1px solid #f2ddab',
        borderRadius: 8,
        padding: '10px 14px',
        marginTop: 14,
        fontSize: 13.5,
        color: '#7c4a03',
      }}
      role="note"
      aria-label="Demo mode notice"
    >
      <span style={{ fontWeight: 700, flexShrink: 0 }}>Demo mode</span>
      <span>
        This assessment was generated by a deterministic synthetic engine — no external AI was
        contacted and no real medical inference was performed. It is for demonstration purposes
        only.
      </span>
    </div>
  )
}

export default function ResultsPage() {
  const { analysisId } = useParams()
  const navigate = useNavigate()
  const { reset } = useFlow()

  const [analysis, setAnalysis] = useState(null)
  const [error, setError] = useState(null)

  useEffect(() => {
    let cancelled = false
    const id = Number(analysisId)
    if (!Number.isFinite(id)) {
      setError('Invalid analysis reference.')
      return
    }
    api
      .getAnalysis(id)
      .then((data) => {
        if (!cancelled) setAnalysis(data)
      })
      .catch((err) => {
        if (!cancelled) setError(err.message)
      })
    return () => {
      cancelled = true
    }
  }, [analysisId])

  function startNew() {
    reset()
    navigate('/profile')
  }

  if (error) {
    return (
      <div className="card">
        <h2>Could not load the assessment</h2>
        <div className="error-box">{error}</div>
        <button className="btn btn-secondary" onClick={startNew}>Start a new assessment</button>
      </div>
    )
  }

  if (!analysis) {
    return (
      <div className="card">
        <Loader message="Loading your assessment…" />
      </div>
    )
  }

  const isDemo = analysis.source === 'demo'
  const displaySummary = isDemo ? stripDemoPrefix(analysis.summary) : analysis.summary

  return (
    <div>
      <Stepper current={4} />

      {/* ── Header card ─────────────────────────────────────────────────── */}
      <div className="card">
        {/* Title row: heading + risk badge on the same baseline */}
        <div style={{ display: 'flex', alignItems: 'center', gap: 12, flexWrap: 'wrap', marginBottom: 4 }}>
          <h2 style={{ margin: 0 }}>Preliminary health summary</h2>
          <RiskBadge level={analysis.risk_level} />
          {analysis.safety_override && (
            <span
              className="demo-chip"
              title="The safety layer raised the risk level based on detected urgent warning signs."
            >
              Safety escalation applied
            </span>
          )}
        </div>

        {/* Demo-mode notice — replaces the raw "DEMO OUTPUT — SYNTHETIC" chip */}
        {isDemo && <DemoNotice />}

        {/* HIGH risk urgent alert */}
        {analysis.risk_level === 'HIGH' && (
          <div className="alert alert-HIGH" style={{ marginTop: 14 }}>
            <strong>Urgent care may be needed.</strong> Based on what you described, please seek
            medical attention promptly. If symptoms are severe or worsening right now, contact
            local emergency services.
          </div>
        )}

        {/* Summary paragraph */}
        <p style={{ marginTop: 14, marginBottom: 0, lineHeight: 1.6 }}>{displaySummary}</p>

        {/* Reported symptoms chips */}
        {analysis.symptoms.length > 0 && (
          <div style={{ marginTop: 16 }}>
            <div className="section-label">Symptoms you reported</div>
            <div className="chips">
              {analysis.symptoms.map((s, i) => (
                <span className="chip" key={i}>{s}</span>
              ))}
            </div>
          </div>
        )}
      </div>

      {/* ── Results grid ────────────────────────────────────────────────── */}
      <div className="results-grid">
        {analysis.red_flags.length > 0 && (
          <Section title="Urgent warning signs detected" span2>
            <div className="alert alert-HIGH" style={{ marginBottom: 0 }}>
              The following urgent signals were found in what you entered. Please seek medical
              attention promptly.
              <ul style={{ marginTop: 8 }}>
                {analysis.red_flags.map((flag, i) => <li key={i}>{flag}</li>)}
              </ul>
            </div>
          </Section>
        )}

        <Section title="Observations">
          <List items={analysis.observations} />
        </Section>

        <Section title="Possible concerns">
          <p style={{ color: 'var(--muted)', fontSize: 13, marginBottom: 10 }}>
            These are possibilities based on general patterns — not diagnoses.
          </p>
          <List items={analysis.possible_concerns} />
        </Section>

        <Section title="Recommended next steps" span2>
          <List items={analysis.recommended_next_steps} marker="→" />
        </Section>

        <Section title="Questions to ask your doctor">
          <List items={analysis.questions_for_doctor} marker="?" />
        </Section>

        <Section title="Limitations of this assessment">
          <p style={{ color: 'var(--muted)', fontSize: 14 }}>{analysis.limitations}</p>
        </Section>
      </div>

      {/* ── Footer card: disclaimer + actions ───────────────────────────── */}
      <div className="card">
        <div className="alert alert-warn" style={{ marginBottom: 16 }}>
          {analysis.disclaimer}
        </div>
        <div className="btn-row" style={{ marginTop: 0 }}>
          <Link to="/history" className="btn btn-secondary">View history</Link>
          <button className="btn btn-primary" onClick={startNew}>Start new assessment</button>
        </div>
      </div>
    </div>
  )
}
